### ISSUE TITLE
Bomb problem

### ISSUE THREAD

**Issue by jorgefandinno** [jorgefandinno/eclingo#67]
I merged changes in branch [jorge/explit-proven-candidates-rebasing](https://github.com/jorgefandinno/eclingo/tree/jorge/explit-proven-candidates-rebasing) and the following error occurs with the ```world_view_builder```.

Can you check it?

```sh
fandinno@IST-jfandinno:~/student-research/eclingo/bomb_problems (jorge/explit-proven-candidates-rebasing)
$eclingo bt_base.lp bt.lp instances/bomb_0010.lp 
Solving...
Traceback (most recent call last):
  File "/home/fandinno/miniconda3/envs/dev-potassco/lib/python3.9/site-packages/clingo/application.py", line 359, in _pyclingo_application_main
    app.main(Control(control), [_to_str(files[i]) for i in range(size)])
  File "/home/fandinno/student-research/eclingo/src/eclingo/main.py", line 117, in main
    for wv_number, world_view in enumerate(eclingo_control.solve(), 1):
  File "/home/fandinno/student-research/eclingo/src/eclingo/control.py", line 81, in solve
    for model in self.solver.solve():
  File "/home/fandinno/student-research/eclingo/src/eclingo/solver/solvers.py", line 56, in solve
    yield self._build_world_view_reification(candidate)
  File "/home/fandinno/student-research/eclingo/src/eclingo/solver/world_view_builder.py", line 20, in __call__
    return self.world_view_from_candidate(candidate)
  File "/home/fandinno/student-research/eclingo/src/eclingo/solver/world_view_builder.py", line 164, in world_view_from_candidate
    assert model is not None
AssertionError
*** ERROR: (eclingo): no message
```

**Comment by lute47lillo** [comment]
I have been looking into it, and it seems that is the handle not generating a model based on the assumptions.

I have seen this issue before way back when first working on the tester, but the only way to fix it is probably re-creating a subset of the problem to a smaller degree, and see where and why it fails to generate this problem. Now is generating 250+ candidates, and is hard to read through.

**Comment by jorgefandinno** [comment]
- Ok, I will wait for that.
